#FROM ubuntu:latest
#LABEL authors="sasha"
#
#ENTRYPOINT ["top", "-b"]


# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the necessary packages
RUN pip install fastapi uvicorn xgboost pandas scikit-learn

# Expose port 8000 to the outside world
EXPOSE 8000

# Run the FastAPI server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]